openapi: 3.0.1
info:
  title: Customer API Application Demo
  description: Customer API Application - Documentation APIs v1.0
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Actuator
  description: Monitor and interact
  externalDocs:
    description: Spring Boot Actuator Web API Documentation
    url: https://docs.spring.io/spring-boot/docs/current/actuator-api/html/
paths:
  /actuator/health/{*path}:
    get:
      tags:
      - Actuator
      operationId: handle
      parameters:
      - name: '*path'
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /actuator/health:
    get:
      tags:
      - Actuator
      operationId: handle_1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /actuator:
    get:
      tags:
      - Actuator
      summary: Actuator root web endpoint
      operationId: links
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/Link'
  /customer:
    get:
      tags:
      - customer-handler
      operationId: getCusomers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      tags:
      - customer-handler
      operationId: addCusomers
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
components:
  schemas:
    Link:
      type: object
      properties:
        href:
          type: string
        templated:
          type: boolean
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
